# -----------------------------------------------------------------------------
# Composite CI & Governance Workflow
# Purpose: run reusable stack tests and validate governance configs
# Usage:
#   uses: splaxtr/.github/.github/workflows/ci-lint.yml@main
# Outputs:
#   status: summary job result
# -----------------------------------------------------------------------------
name: â™»ï¸ Composite CI Matrix

on:
  workflow_dispatch:
  pull_request:
  workflow_call:
    outputs:
      status:
        description: "Workflow result"
        value: ${{ jobs.summary.result }}
    inputs:
      node_enabled:
        type: boolean
        default: true
      node_version:
        type: string
        default: "20.x"
      node_working_directory:
        type: string
        default: "frontend"
      node_package_manager:
        type: string
        default: "npm"
      python_enabled:
        type: boolean
        default: true
      python_version:
        type: string
        default: "3.11"
      python_working_directory:
        type: string
        default: "bots/python"
      go_enabled:
        type: boolean
        default: true
      go_version:
        type: string
        default: "1.22.x"
      go_working_directory:
        type: string
        default: "backend"
      flutter_enabled:
        type: boolean
        default: true
      flutter_version:
        type: string
        default: "3.24.0"
      flutter_channel:
        type: string
        default: "stable"
      flutter_working_directory:
        type: string
        default: "mobile"
      bun_enabled:
        type: boolean
        default: false
      bun_working_directory:
        type: string
        default: "frontend"
      bun_version:
        type: string
        default: "latest"
      security_enabled:
        type: boolean
        default: true
      docker_context:
        type: string
        default: "."

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  governance:
    name: Governance checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install lint tools
        run: |
          python3 -m pip install --upgrade pip
          pip install yamllint markdownlint-cli
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- -b /usr/local/bin latest
      - name: Run governance lint
        run: |
          set -e
          yamllint .github/ | tee governance-yamllint.log
          actionlint -color | tee governance-actionlint.log
          markdownlint "**/*.md" | tee governance-markdownlint.log
          cat governance-*.log > governance.log
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-governance-${{ github.sha }}
          path: governance.log
          if-no-files-found: warn

  node:
    needs: governance
    if: ${{ inputs.node_enabled }}
    uses: ./.github/workflows/reusable-node-ci.yml
    with:
      node_version: ${{ inputs.node_version }}
      working_directory: ${{ inputs.node_working_directory }}
      package_manager: ${{ inputs.node_package_manager }}
      artifact_path: "dist"

  bun:
    needs: governance
    if: ${{ inputs.bun_enabled }}
    uses: ./.github/workflows/reusable-bun-ci.yml
    with:
      bun_version: ${{ inputs.bun_version }}
      working_directory: ${{ inputs.bun_working_directory }}

  python:
    needs: governance
    if: ${{ inputs.python_enabled }}
    uses: ./.github/workflows/reusable-python-ci.yml
    with:
      python_version: ${{ inputs.python_version }}
      working_directory: ${{ inputs.python_working_directory }}

  go:
    needs: governance
    if: ${{ inputs.go_enabled }}
    uses: ./.github/workflows/reusable-go-ci.yml
    with:
      go_version: ${{ inputs.go_version }}
      working_directory: ${{ inputs.go_working_directory }}
      docker_context: ${{ inputs.go_working_directory }}

  flutter:
    needs: governance
    if: ${{ inputs.flutter_enabled }}
    uses: ./.github/workflows/reusable-flutter-ci.yml
    with:
      flutter_version: ${{ inputs.flutter_version }}
      flutter_channel: ${{ inputs.flutter_channel }}
      working_directory: ${{ inputs.flutter_working_directory }}

  security:
    needs: governance
    if: ${{ inputs.security_enabled }}
    uses: ./.github/workflows/reusable-security.yml
    with:
      working-directory: ${{ inputs.docker_context }}

  summary:
    name: ðŸ“Š CI Summary
    runs-on: ubuntu-latest
    needs:
      - governance
      - node
      - bun
      - python
      - go
      - flutter
      - security
    if: always()
    steps:
      - name: Job summary
        run: |
          echo "## Composite CI status" >> $GITHUB_STEP_SUMMARY
          echo "- Governance: ${{ needs.governance.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Node: ${{ needs.node.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Bun: ${{ needs.bun.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Python: ${{ needs.python.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Go: ${{ needs.go.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Flutter: ${{ needs.flutter.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Security: ${{ needs.security.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          cat <<'TABLE' > ci-summary.md
          | Job | Status |
          | --- | --- |
          | Governance | ${{ needs.governance.result }} |
          | Node | ${{ needs.node.result || 'skipped' }} |
          | Bun | ${{ needs.bun.result || 'skipped' }} |
          | Python | ${{ needs.python.result || 'skipped' }} |
          | Go | ${{ needs.go.result || 'skipped' }} |
          | Flutter | ${{ needs.flutter.result || 'skipped' }} |
          | Security | ${{ needs.security.result || 'skipped' }} |
          TABLE
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}-summary-${{ github.sha }}
          path: ci-summary.md
          if-no-files-found: warn
      - name: Expose status output
        if: always()
        run: echo "status=${{ job.status }}" >> $GITHUB_OUTPUT
