# Composite CI workflow that orchestrates the reusable stacks for end-to-end verification.
name: â™»ï¸ Composite CI Matrix

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      node_enabled:
        type: boolean
        default: true
      node_version:
        type: string
        default: "20.x"
      node_working_directory:
        type: string
        default: "frontend"
      node_package_manager:
        type: string
        default: "npm"
      python_enabled:
        type: boolean
        default: true
      python_version:
        type: string
        default: "3.11"
      python_working_directory:
        type: string
        default: "bots/python"
      go_enabled:
        type: boolean
        default: true
      go_version:
        type: string
        default: "1.22.x"
      go_working_directory:
        type: string
        default: "backend"
      flutter_enabled:
        type: boolean
        default: true
      flutter_version:
        type: string
        default: "3.24.0"
      flutter_channel:
        type: string
        default: "stable"
      flutter_working_directory:
        type: string
        default: "mobile"
      bun_enabled:
        type: boolean
        default: false
      bun_working_directory:
        type: string
        default: "frontend"
      bun_version:
        type: string
        default: "latest"
      security_enabled:
        type: boolean
        default: true
      docker_context:
        type: string
        default: "."

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  node:
    if: ${{ inputs.node_enabled }}
    uses: ./.github/workflows/reusable-node-ci.yml
    with:
      node_version: ${{ inputs.node_version }}
      working_directory: ${{ inputs.node_working_directory }}
      package_manager: ${{ inputs.node_package_manager }}
      artifact_path: "dist"

  bun:
    if: ${{ inputs.bun_enabled }}
    uses: ./.github/workflows/reusable-bun-ci.yml
    with:
      bun_version: ${{ inputs.bun_version }}
      working_directory: ${{ inputs.bun_working_directory }}

  python:
    if: ${{ inputs.python_enabled }}
    uses: ./.github/workflows/reusable-python-ci.yml
    with:
      python_version: ${{ inputs.python_version }}
      working_directory: ${{ inputs.python_working_directory }}

  go:
    if: ${{ inputs.go_enabled }}
    uses: ./.github/workflows/reusable-go-ci.yml
    with:
      go_version: ${{ inputs.go_version }}
      working_directory: ${{ inputs.go_working_directory }}
      docker_context: ${{ inputs.go_working_directory }}

  flutter:
    if: ${{ inputs.flutter_enabled }}
    uses: ./.github/workflows/reusable-flutter-ci.yml
    with:
      flutter_version: ${{ inputs.flutter_version }}
      flutter_channel: ${{ inputs.flutter_channel }}
      working_directory: ${{ inputs.flutter_working_directory }}

  security:
    if: ${{ inputs.security_enabled }}
    uses: ./.github/workflows/reusable-security.yml
    with:
      working-directory: ${{ inputs.docker_context }}

  summary:
    name: ðŸ“Š CI Summary
    runs-on: ubuntu-latest
    needs: [node, bun, python, go, flutter, security]
    if: always()
    steps:
      - name: Job summary
        run: |
          echo "## Composite CI status" >> $GITHUB_STEP_SUMMARY
          echo "- Node: ${{ needs.node.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Bun: ${{ needs.bun.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Python: ${{ needs.python.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Go: ${{ needs.go.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Flutter: ${{ needs.flutter.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Security: ${{ needs.security.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
