# Reusable label sync workflow to keep issue/PR labels in sync across repositories.
name: â™»ï¸ Reusable Label Sync

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      labels_file:
        type: string
        default: ".github/labels.yml"
      dry_run:
        type: boolean
        default: false
      collect_stats:
        type: boolean
        default: true

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    name: ðŸ”„ Sync labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: ${{ inputs.labels_file }}
          skip-delete: false
          dry-run: ${{ inputs.dry_run }}

      - name: Summary
        run: |
          echo "### Label sync" >> $GITHUB_STEP_SUMMARY
          echo "- File: ${{ inputs.labels_file }}" >> $GITHUB_STEP_SUMMARY
          echo "- Dry run: ${{ inputs.dry_run }}" >> $GITHUB_STEP_SUMMARY

  stats:
    name: ðŸ“ˆ Label stats
    needs: sync
    if: ${{ inputs.collect_stats && !inputs.dry_run }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Collect stats
        run: |
          TOTAL=$(grep -c "^- name:" ${{ inputs.labels_file }} || true)
          echo "### Label stats" >> $GITHUB_STEP_SUMMARY
          echo "- Total labels: $TOTAL" >> $GITHUB_STEP_SUMMARY

  validate:
    name: âœ… Validate YAML
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install validator deps
        run: pip install pyyaml

      - name: Validate schema
        run: |
          python - <<'PY'
import sys, yaml
path = "${{ inputs.labels_file }}"
try:
    with open(path, 'r', encoding='utf-8') as fh:
        data = yaml.safe_load(fh)
    if not isinstance(data, list):
        raise ValueError('Labels file must be a list of entries')
    missing = [item for item in data if 'name' not in item or 'color' not in item]
    if missing:
        raise ValueError('Some labels are missing name/color fields')
    print('Labels YAML validated successfully')
except Exception as exc:
    print(f'Validation failed: {exc}')
    sys.exit(1)
PY
