# -----------------------------------------------------------------------------
# Release Drafter Workflow
# Purpose: keep draft releases up to date with semantic labels
# Usage:
#   uses: splaxtr/.github/.github/workflows/release-drafter.yml@main
# Outputs:
#   status: job result (success|failure)
# -----------------------------------------------------------------------------
name: ♻️ Reusable Release Drafter

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      status:
        description: "Workflow result"
        value: ${{ jobs.release.result }}
    inputs:
      config_path:
        type: string
        default: ".github/release-drafter.yml"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure config exists
        id: config
        run: |
          if [ ! -f "${{ inputs.config_path }}" ]; then
            echo "missing=true" >> $GITHUB_OUTPUT
            echo "::error::Release drafter config not found"
            exit 1
          fi
          echo "missing=false" >> $GITHUB_OUTPUT

      - name: Update draft release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: ${{ inputs.config_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "### Release drafter" >> $GITHUB_STEP_SUMMARY
          echo "- Config: ${{ inputs.config_path }}" >> $GITHUB_STEP_SUMMARY
          echo "status=${{ job.status }}" >> $GITHUB_OUTPUT
