# Reusable Python CI workflow for linting, formatting, testing, and packaging Python projects.
name: ♻️ Reusable Python CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      python_version:
        description: "Python version to install"
        required: false
        type: string
        default: "3.11"
      working_directory:
        description: "Directory that contains the Python project"
        required: false
        type: string
        default: "."
      lint_command:
        description: "Lint command"
        required: false
        type: string
        default: "ruff check ."
      format_command:
        description: "Formatter command that runs in check mode"
        required: false
        type: string
        default: "black --check ."
      test_command:
        description: "Pytest command (or any test runner)"
        required: false
        type: string
        default: "pytest --maxfail=1 --disable-warnings --cov=. --cov-report=xml"
      coverage_file:
        description: "Coverage artifact path"
        required: false
        type: string
        default: "coverage.xml"
      run_tests:
        description: "Toggle test execution"
        required: false
        type: boolean
        default: true
      upload_artifacts:
        description: "Upload .pytest_cache and coverage files"
        required: false
        type: boolean
        default: true

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  python-ci:
    name: Python build + test pipeline
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          cache: pip

      - name: Cache virtual environment
        uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.working_directory }}/.venv
            ${{ inputs.working_directory }}/.pytest_cache
          key: ${{ runner.os }}-python-${{ inputs.python_version }}-${{ hashFiles(format('{0}/requirements*.txt', inputs.working_directory)) }}
          restore-keys: |
            ${{ runner.os }}-python-${{ inputs.python_version }}-
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if find . -maxdepth 1 -name "requirements*.txt" | grep -q .; then
            pip install -r requirements.txt || true
            for file in requirements-dev.txt requirements-ci.txt; do
              if [ -f "$file" ]; then
                pip install -r "$file"
              fi
            done
          fi
          pip install pytest coverage ruff black

      - name: Run formatter checks
        run: ${{ inputs.format_command }}

      - name: Run lint
        run: ${{ inputs.lint_command }}

      - name: Run tests
        if: ${{ inputs.run_tests }}
        run: ${{ inputs.test_command }}

      - name: Upload artifacts
        if: ${{ inputs.upload_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts-${{ github.sha }}
          path: |
            ${{ inputs.working_directory }}/.pytest_cache
            ${{ inputs.working_directory }}/${{ inputs.coverage_file }}
          if-no-files-found: warn

      - name: Summarize job
        if: always()
        run: |
          echo "### Python CI" >> $GITHUB_STEP_SUMMARY
          echo "- Python version: ${{ inputs.python_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- Working directory: ${{ inputs.working_directory }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tests executed: ${{ inputs.run_tests }}" >> $GITHUB_STEP_SUMMARY
