# Reusable multi-service deploy workflow orchestrating backend, frontend, mobile, and bots releases.
name: â™»ï¸ Reusable Deploy Pipeline

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: "GitHub environment / target stage"
        required: false
        type: string
        default: "production"
      force_deploy:
        description: "Ignore change detection and deploy anyway"
        required: false
        type: boolean
        default: false
      changed_services:
        description: "Comma separated list of services to deploy (backend,frontend,mobile,bots)"
        required: false
        type: string
        default: ""
      node_version:
        description: "Node.js version for frontend/bots"
        required: false
        type: string
        default: "20.x"
      python_version:
        description: "Python version for automation/bots"
        required: false
        type: string
        default: "3.11"
      go_version:
        description: "Go version for backend"
        required: false
        type: string
        default: "1.22.x"
      flutter_version:
        description: "Flutter version for mobile builds"
        required: false
        type: string
        default: "3.24.0"
      flutter_channel:
        description: "Flutter channel"
        required: false
        type: string
        default: "stable"
      docker_context:
        description: "Context used for backend image builds"
        required: false
        type: string
        default: "backend"
      run_smoke_tests:
        description: "Execute smoke tests once deploy jobs finish"
        required: false
        type: boolean
        default: true

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  DEPLOY_ENV: ${{ inputs.environment }}

jobs:
  plan:
    name: ðŸ” Detect changes
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.services }}
      should_deploy: ${{ steps.detect.outputs.should_deploy }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Discover services to deploy
        id: detect
        run: |
          INPUT_SERVICES="${{ inputs.changed_services }}"
          if [ -n "$INPUT_SERVICES" ]; then
            SERVICES=$(echo "$INPUT_SERVICES" | tr '[:upper:]' '[:lower:]' | sed 's/ //g')
          else
            CHANGED=$(git diff --name-only HEAD^ HEAD || git ls-files)
            SERVICES=""
            for service in backend frontend mobile bots; do
              if echo "$CHANGED" | grep -q "${service}/"; then
                SERVICES+="$service,"
              fi
            done
            SERVICES=${SERVICES%,}
          fi

          if [ -z "$SERVICES" ] && [ "${{ inputs.force_deploy }}" != "true" ]; then
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            echo "services=" >> $GITHUB_OUTPUT
            echo "No services changed."
          else
            if [ -z "$SERVICES" ]; then
              SERVICES="backend,frontend,mobile,bots"
            fi
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "services=$SERVICES" >> $GITHUB_OUTPUT
          fi

      - name: Append plan summary
        run: |
          echo "### Deployment plan" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- Services: ${{ steps.detect.outputs.services || 'none' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Forced: ${{ inputs.force_deploy }}" >> $GITHUB_STEP_SUMMARY

  backend:
    name: ðŸ¹ Backend
    needs: plan
    if: ${{ needs.plan.outputs.should_deploy == 'true' && contains(needs.plan.outputs.services, 'backend') }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache: true

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ inputs.docker_context }}/bin
          key: backend-${{ runner.os }}-${{ hashFiles(format('{0}/go.sum', inputs.docker_context)) }}

      - name: Run tests
        working-directory: ${{ inputs.docker_context }}
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Build binary
        working-directory: ${{ inputs.docker_context }}
        run: go build -o bin/app ./cmd/...

      - name: Build & push container
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.docker_context }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy (kubectl)
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          if [ -z "$KUBECONFIG" ]; then
            echo "KUBECONFIG secret missing; skipping kubectl" && exit 0
          fi
          kubectl set image deployment/backend api=ghcr.io/${{ github.repository }}-backend:${{ github.sha }} -n $DEPLOY_ENV
          kubectl rollout status deployment/backend -n $DEPLOY_ENV --timeout=300s

  frontend:
    name: ðŸŒ Frontend
    needs: plan
    if: ${{ needs.plan.outputs.should_deploy == 'true' && contains(needs.plan.outputs.services, 'frontend') }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: frontend-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install & test
        working-directory: frontend
        run: |
          npm ci
          npm run lint
          npm test -- --watch=false

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Deploy (Vercel)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        working-directory: frontend
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "Missing Vercel token; skipping deploy"
          else
            npx vercel --prod --token=$VERCEL_TOKEN --confirm
          fi

  mobile:
    name: ðŸ“± Mobile
    needs: plan
    if: ${{ needs.plan.outputs.should_deploy == 'true' && contains(needs.plan.outputs.services, 'mobile') }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: ${{ inputs.flutter_channel }}
          cache: true

      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            mobile/.dart_tool
          key: mobile-${{ runner.os }}-${{ hashFiles('mobile/pubspec.lock') }}

      - name: Test & build artifacts
        working-directory: mobile
        run: |
          flutter pub get
          flutter test
          flutter build apk --release --split-per-abi
          flutter build ios --release --no-codesign

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mobile-build-${{ github.sha }}
          path: |
            mobile/build/app/outputs/flutter-apk/*.apk
            mobile/build/ios/ipa
          if-no-files-found: warn

  bots:
    name: ðŸ¤– Bots
    needs: plan
    if: ${{ needs.plan.outputs.should_deploy == 'true' && contains(needs.plan.outputs.services, 'bots') }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        runtime: [node, python]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node runtime
        if: ${{ matrix.runtime == 'node' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
          cache-dependency-path: bots/node/package-lock.json

      - name: Setup Python runtime
        if: ${{ matrix.runtime == 'python' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          cache: pip

      - name: Install bot dependencies
        run: |
          if [ "${{ matrix.runtime }}" = "node" ]; then
            cd bots/node && npm ci && npm run build
          else
            cd bots/python && python -m pip install --upgrade pip && pip install -r requirements.txt
          fi

      - name: Deploy bot workloads
        env:
          BOT_TOKEN: ${{ secrets.BOTS_DEPLOY_TOKEN }}
        run: |
          if [ -z "$BOT_TOKEN" ]; then
            echo "BOT token missing; skipping"
          else
            echo "Deploying ${{ matrix.runtime }} bots"
          fi

  database:
    name: ðŸ—„ï¸ Database migrations
    needs: [plan, backend]
    if: ${{ needs.plan.outputs.should_deploy == 'true' && contains(needs.plan.outputs.services, 'backend') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      - name: Run migrations
        working-directory: ${{ inputs.docker_context }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "DATABASE_URL missing" && exit 1
          fi
          go run cmd/migrate/main.go

  smoke-tests:
    name: ðŸ§ª Smoke tests
    needs: [backend, frontend, bots]
    if: ${{ inputs.run_smoke_tests && needs.plan.outputs.should_deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Hit health endpoints
        run: |
          curl -f https://api.example.com/health || exit 1
          curl -f https://example.com || exit 1

  summary:
    name: ðŸ“‹ Deployment summary
    runs-on: ubuntu-latest
    needs: [plan, backend, frontend, mobile, bots, database, smoke-tests]
    if: always()
    steps:
      - name: Publish summary
        run: |
          echo "## Deployment summary" >> $GITHUB_STEP_SUMMARY
          echo "- Env: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- Services: ${{ needs.plan.outputs.services }}" >> $GITHUB_STEP_SUMMARY
          echo "- Backend: ${{ needs.backend.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Frontend: ${{ needs.frontend.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Mobile: ${{ needs.mobile.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Bots: ${{ needs.bots.result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Smoke: ${{ needs['smoke-tests'].result || 'skipped' }}" >> $GITHUB_STEP_SUMMARY
