# Reusable Monorepo CI workflow to fan-out Node, Bun, Python, Go, and Flutter checks in one run.
name: â™»ï¸ Reusable Monorepo CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: "20.x"
        description: "Node.js version for the Node service"
      node_path:
        type: string
        default: "services/node-app"
        description: "Path to the Node service"
      bun_version:
        type: string
        default: "latest"
        description: "Bun version for the Bun service"
      bun_path:
        type: string
        default: "services/bun-app"
      python_version:
        type: string
        default: "3.11"
      python_path:
        type: string
        default: "services/python-app"
      go_version:
        type: string
        default: "1.22.x"
      go_path:
        type: string
        default: "services/go-app"
      flutter_version:
        type: string
        default: "3.24.0"
      flutter_channel:
        type: string
        default: "stable"
      flutter_path:
        type: string
        default: "services/flutter-app"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  nodejs:
    name: ðŸŸ¢ Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
          cache-dependency-path: ${{ inputs.node_path }}/package-lock.json

      - uses: actions/cache@v4
        with:
          path: ${{ inputs.node_path }}/node_modules
          key: node-${{ runner.os }}-${{ hashFiles(format('{0}/package-lock.json', inputs.node_path)) }}

      - name: Install + lint + test
        working-directory: ${{ inputs.node_path }}
        run: |
          npm ci
          npm run lint
          npm test -- --coverage

      - uses: actions/upload-artifact@v4
        with:
          name: node-coverage-${{ github.sha }}
          path: ${{ inputs.node_path }}/coverage
          if-no-files-found: warn

  bunjs:
    name: ðŸŸ£ Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun_version }}

      - uses: actions/cache@v4
        with:
          path: ${{ inputs.bun_path }}/node_modules
          key: bun-${{ runner.os }}-${{ hashFiles(format('{0}/bun.lockb', inputs.bun_path)) }}

      - name: Install + lint + test
        working-directory: ${{ inputs.bun_path }}
        run: |
          bun install --frozen-lockfile
          bun run lint
          bun run test --coverage

      - uses: actions/upload-artifact@v4
        with:
          name: bun-coverage-${{ github.sha }}
          path: ${{ inputs.bun_path }}/coverage
          if-no-files-found: warn

  python:
    name: ðŸ Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          cache: pip

      - uses: actions/cache@v4
        with:
          path: |
            ${{ inputs.python_path }}/.venv
            ${{ inputs.python_path }}/.pytest_cache
          key: python-${{ runner.os }}-${{ hashFiles(format('{0}/requirements.txt', inputs.python_path)) }}

      - name: Install + lint + test
        working-directory: ${{ inputs.python_path }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8
          flake8 .
          pytest --cov=. --cov-report=xml

      - uses: actions/upload-artifact@v4
        with:
          name: python-coverage-${{ github.sha }}
          path: ${{ inputs.python_path }}/coverage.xml
          if-no-files-found: warn

  golang:
    name: ðŸ”µ Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ${{ inputs.go_path }}/bin
          key: go-${{ runner.os }}-${{ hashFiles(format('{0}/go.sum', inputs.go_path)) }}

      - name: Install + lint + test
        working-directory: ${{ inputs.go_path }}
        run: |
          go mod tidy
          go test ./... -coverprofile=coverage.out

      - uses: actions/upload-artifact@v4
        with:
          name: go-coverage-${{ github.sha }}
          path: ${{ inputs.go_path }}/coverage.out
          if-no-files-found: warn

  flutter:
    name: ðŸ’™ Flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: ${{ inputs.flutter_channel }}
          cache: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ${{ inputs.flutter_path }}/.dart_tool
            ${{ inputs.flutter_path }}/build
          key: flutter-${{ runner.os }}-${{ hashFiles(format('{0}/pubspec.lock', inputs.flutter_path)) }}

      - name: Test Flutter app
        working-directory: ${{ inputs.flutter_path }}
        run: |
          flutter pub get
          flutter analyze
          flutter test --coverage

      - uses: actions/upload-artifact@v4
        with:
          name: flutter-coverage-${{ github.sha }}
          path: ${{ inputs.flutter_path }}/coverage/lcov.info
          if-no-files-found: warn

  summary:
    name: ðŸ“¢ Summary
    runs-on: ubuntu-latest
    needs: [nodejs, bunjs, python, golang, flutter]
    if: always()
    steps:
      - name: Report status
        run: |
          echo "## Monorepo CI status" >> $GITHUB_STEP_SUMMARY
          echo "- nodejs: ${{ needs.nodejs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- bunjs: ${{ needs.bunjs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- python: ${{ needs.python.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- golang: ${{ needs.golang.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- flutter: ${{ needs.flutter.result }}" >> $GITHUB_STEP_SUMMARY
