# Reusable Docker build workflow that builds/pushes GHCR images with caching and metadata.
name: ♻️ Reusable Docker Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      docker_context:
        description: "Build context"
        required: false
        type: string
        default: "."
      dockerfile:
        description: "Dockerfile path"
        required: false
        type: string
        default: "Dockerfile"
      platforms:
        description: "Comma separated list of target platforms"
        required: false
        type: string
        default: "linux/amd64,linux/arm64"
      push_image:
        description: "Push image to GHCR"
        required: false
        type: boolean
        default: true
      build_args:
        description: "Optional multiline build args"
        required: false
        type: string
        default: ""

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docker:
    name: Docker build & push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lowercase image name
        id: image
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          echo "name=${IMAGE,,}" >> $GITHUB_OUTPUT

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image.outputs.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Login to GHCR
        if: ${{ inputs.push_image }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and (optionally) push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.docker_context }}/${{ inputs.dockerfile }}
          push: ${{ inputs.push_image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ inputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_SHA=${{ github.sha }}
            BUILD_REF=${{ github.ref_name }}
            ${{ inputs.build_args }}

      - name: Summarize build
        run: |
          echo "### Docker build" >> $GITHUB_STEP_SUMMARY
          echo "- Image: ${{ steps.image.outputs.name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tags: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
